const productsData = [
  {id: 0, productName: 'John Doe', productSupply: '1', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 1, productName: 'Samppa Nori', productSupply: '5', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 2, productName: 'Estavan Lykos', productSupply: '6', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 3, productName: 'Chetan Mohamed', productSupply: '0', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 4, productName: 'Derick Maximinus', productSupply: '20', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 5, productName: 'Friderik Dávid', productSupply: '7', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 6, productName: 'Yiorgos Avraamu', productSupply: '6', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 7, productName: 'Avram Tarasios', productSupply: '50', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 8, productName: 'Quintin Ed', productSupply: '40', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 9, productName: 'Enéas Kwadwo', productSupply: '35', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 10, productName: 'Agapetus Tadeáš', productSupply: '2', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 11, productName: 'Carwyn Fachtna', productSupply: '0', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 12, productName: 'Nehemiah Tatius', productSupply: '50', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 13, productName: 'Ebbe Gemariah', productSupply: '15', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 14, productName: 'Eustorgios Amulius', productSupply: '13', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 15, productName: 'Leopold Gáspár', productSupply: '45', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 16, productName: 'Pompeius René', productSupply: '0', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 17, productName: 'Paĉjo Jadon', productSupply: '31', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 18, productName: 'Micheal Mercurius', productSupply: '12', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 19, productName: 'Ganesha Dubhghall', productSupply: '10', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 20, productName: 'Hiroto Šimun', productSupply: '0', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 21, productName: 'Vishnu Serghei', productSupply: '2', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 22, productName: 'Zbyněk Phoibos', productSupply: '18', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 23, productName: 'Einar Randall', productSupply: '9', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 24, productName: 'Félix Troels', productSupply: '26', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 25, productName: 'Aulus Agmundr', productSupply: '19', productPrice: '10000',productImage:'some image will been shown here'},
  {id: 42, productName: 'Ford Prefex', productSupply: '31', productPrice: '10000',productImage:'some image will been shown here'}
]

export default productsData